package sudokuproject.io;

import model.SudokuBoard;
import java.io.*;

/**
 * This class is responsible for printing and saving Sudoku boards.
 * It works directly with SudokuBoard using getValue(row, col).
 */
public class PuzzleWriter {

    // Board and box size taken from SudokuBoard constants
    private static final int BOARD_SIZE = SudokuBoard.SIZE;
    private static final int BOX_SIZE = SudokuBoard.SUBGRID_SIZE;

    /**
     * Prints the board on the console with a formatted layout.
     * @param board
     */
    public void printToConsole(SudokuBoard board) {
        printToConsole(board, null);
    }

    /**
     * Prints the board on the console and shows a title above it (optional).
     * If title is null or empty, nothing is printed above the board.
     * @param board
     * @param title
     */
    public void printToConsole(SudokuBoard board, String title) {
        if (title != null && !title.isEmpty()) {
            System.out.println("\n" + title);
            System.out.println("=".repeat(title.length()));
        }
        System.out.println(formatBoard(board));
    }

    /**
     * Saves the Sudoku board into a file.
     * The file will contain both the formatted board and raw values.
     * @param board
     * @param filename
     * @throws java.io.IOException
     */
    public void writeToFile(SudokuBoard board, String filename) throws IOException {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filename))) {

            writer.write("# Sudoku Solution\n");
            writer.write("# Generated by Parallel Sudoku Solver\n\n");

            // Formatted board
            writer.write(formatBoard(board));

            // Raw board (easy to load later)
            writer.write("\n\n# Raw format (space-separated):\n");
            writer.write(exportToString(board));
        }
    }

    /**
     * Converts the Sudoku board into a simple text form.
     * Each row is one line, values separated by spaces.
     * This format is good for saving and loading.
     * @param board
     * @return 
     */
    public String exportToString(SudokuBoard board) {
        StringBuilder sb = new StringBuilder();

        for (int row = 0; row < BOARD_SIZE; row++) {
            for (int col = 0; col < BOARD_SIZE; col++) {
                sb.append(board.getValue(row, col));
                if (col < BOARD_SIZE - 1) sb.append(" ");
            }
            if (row < BOARD_SIZE - 1) sb.append("\n");
        }
        return sb.toString();
    }

    /**
     * Creates the formatted Sudoku grid as a string.
     * Box separators every 3 rows and columns.
     * Empty cells (0) appear as dots for readability.
     */
    private String formatBoard(SudokuBoard board) {
        StringBuilder sb = new StringBuilder();

        sb.append(createHorizontalLine()).append("\n");

        for (int row = 0; row < BOARD_SIZE; row++) {

            sb.append("| ");

            for (int col = 0; col < BOARD_SIZE; col++) {
                int value = board.getValue(row, col);

                sb.append(value == 0 ? ". " : value + " ");

                if ((col + 1) % BOX_SIZE == 0) sb.append("| ");
            }

            sb.append("\n");

            if ((row + 1) % BOX_SIZE == 0) {
                sb.append(createHorizontalLine()).append("\n");
            }
        }

        return sb.toString();
    }

    /**
     * Creates the horizontal grid border, for example:
     * +-------+-------+-------+
     */
    private String createHorizontalLine() {
        return "+-------+-------+-------+";
    }

    /**
     * Prints the original puzzle next to its solved version.
     * Also prints whether the solved board is complete and valid.
     * @param original
     * @param solved
     */
    public void printComparison(SudokuBoard original, SudokuBoard solved) {
        System.out.println("\n========== SUDOKU COMPARISON ==========");

        System.out.println("\nORIGINAL PUZZLE:");
        System.out.println(formatBoard(original));

        System.out.println("\nSOLVED PUZZLE:");
        System.out.println(formatBoard(solved));

        if (solved.isComplete()) {
            System.out.println("✓ Solution is COMPLETE and VALID!");
        } else {
            System.out.println("⚠ Solution is INCOMPLETE or INVALID");
        }

        System.out.println("========================================\n");
    }

    /**
     * Prints information about how many cells are filled, empty,
     * and the percentage of the board that is filled.
     * @param board
     */
    public void printStatistics(SudokuBoard board) {
        int empty = 0;
        int filled = 0;

        for (int row = 0; row < BOARD_SIZE; row++) {
            for (int col = 0; col < BOARD_SIZE; col++) {
                if (board.getValue(row, col) == 0) empty++;
                else filled++;
            }
        }

        double percent = (filled * 100.0) / (BOARD_SIZE * BOARD_SIZE);

        System.out.println("\n--- Board Statistics ---");
        System.out.println("Total cells: 81");
        System.out.println("Filled cells: " + filled);
        System.out.println("Empty cells: " + empty);
        System.out.printf("Fill percentage: %.1f%%\n", percent);

        if (board.isComplete()) {
            System.out.println("Status: ✓ COMPLETE & VALID");
        } else if (empty == 0) {
            System.out.println("Status: ✗ FILLED but INVALID");
        } else {
            System.out.println("Status: INCOMPLETE");
        }

        System.out.println("------------------------\n");
    }

    /**
     * Prints details about whether the board is valid or incomplete.
     * Mostly used for debugging when loading puzzles.
     * @param board
     */
    public void printValidationInfo(SudokuBoard board) {
        int empty = 0;

        for (int row = 0; row < BOARD_SIZE; row++) {
            for (int col = 0; col < BOARD_SIZE; col++) {
                if (board.getValue(row, col) == 0) empty++;
            }
        }

        System.out.println("\n--- Validation Info ---");
        System.out.println("Empty cells: " + empty);
        System.out.println("Filled cells: " + (81 - empty));

        if (board.isComplete()) {
            System.out.println("Board status: ✓ Complete and valid");
        } else if (empty > 0) {
            System.out.println("Board status: Partially filled");
        } else {
            System.out.println("Board status: ✗ Filled but invalid");
        }

        System.out.println("-----------------------\n");
    }
}
